### ISSUE TITLE
Unable to Open Images if set to default App

### ISSUE THREAD

**Issue by stutzzzz** [ImEditor/ImEditor#20]
Using PoPos 19.04 Gnome DE wayland when using the app as default for Photos I am unable to open any files. But If I open it from the App it is able to open it.

**Comment by Huluti** [comment]
Thank you for your report, this should be fixed now. I'll release 0.9.3 soon.

**Comment by Huluti** [comment]
Needs an other fix.

**Comment by Huluti** [comment]
@MikeStutzzzz you can now update ImEditor ;)

**Comment by stutzzzz** [comment]
Thanks that's working
