### ISSUE TITLE
Copy image to clipboard

### ISSUE THREAD

**Issue by xi1976github** [ImEditor/ImEditor#26]
I am not able to copy an Image or a selectdion of an image into clipboard, neither via 3-lines-menu nor via shortcut ctrl+c. Am I misunderstanding this function?

**Comment by Huluti** [comment]
HI! The copy function was indeed just for intern purpose. I don't spend time developing the app these days, but I will try your PR. I'll keep you posted very quickly. Thank's for your interest.
